-- Execute once in Supabase SQL Editor before enabling "La plume du jour".
create table if not exists public.plumes_du_jour (
  id bigint generated by default as identity primary key,
  publication_date date not null unique,
  categorie text not null,
  texte text not null check (char_length(trim(texte)) between 1 and 2000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.plumes_du_jour add column if not exists categorie text not null default 'Deuil';
alter table public.plumes_du_jour enable row level security;
-- No browser role has direct access. The server API checks dates and privileges.
revoke all on table public.plumes_du_jour from anon, authenticated;
revoke all on sequence public.plumes_du_jour_id_seq from anon, authenticated;
create index if not exists plumes_du_jour_date_idx on public.plumes_du_jour (publication_date desc);
